In [1]:
import pandas as pd

beehiv = pd.read_csv("/Users/benediktas/Desktop/tech europe/beehiiv_subscribers.csv")
luma_hackathon_checkins = pd.read_csv("/Users/benediktas/Desktop/tech europe/luma_hackathon_checkins.csv")
tally_cofounder = pd.read_csv("/Users/benediktas/Desktop/tech europe/tally_cofounder_matching.csv")
tally_hackathon_submissions = pd.read_csv("/Users/benediktas/Desktop/tech europe/tally_hackathon_submissions.csv")
tally_weekly_contact = pd.read_csv("/Users/benediktas/Desktop/tech europe/tally_weekly_contact_requests.csv")

luma_hackathon_checkins.head(3)

,api_id,name,first_name,last_name,email,phone_number,created_at,approval_status,checked_in_at,custom_source,...,survey_response_feedback,ticket_type_id,ticket_name,What is your LinkedIn profile?,What company do you work for?,What is your job title?,Link to something you've built,Whats your most impressive achievement in the last 3 years?,What is your main goal for this hackathon?,Terms and Conditions
0,gst-GoEd9Sf53GRx8ffi,Cameron Martin,Cameron,Martin,cameronmar@pm.me,NaN,2026-02-18T15:15:48.000Z,approved,2026-02-21T02:52:18.000Z,NaN,...,Best hackathon I have been to in London. Will ...,evtticktyp-ENG0000001,Engineer,https://linkedin.com/in/cameron-martin-748,Stripe,ML Engineer,https://huggingface.co/spaces/cameron-martin,Led technical due diligence for a €20M Series ...,Find a co-founder with complementary skills.,Agreed
1,gst-hwVCC0fYsRLn1jS8,Diego Yilmaz,Diego,Yilmaz,diego12@hey.com,NaN,2026-02-16T19:18:59.000Z,approved,2026-02-21T00:47:01.000Z,NaN,...,Amazing community. The talks before hacking st...,evtticktyp-ENG0000001,Engineer,https://linkedin.com/in/diego-yilmaz-346,Klarna,Solutions Architect,NaN,Rebuilt the data platform for a Series B start...,Build something I can show to early customers.,Agreed
2,gst-4e9mOYf0Yh6d5ASE,Harley Ferrari,Harley,Ferrari,harleyfer@gmail.com,NaN,2026-02-17T11:06:20.000Z,approved,2026-02-21T02:44:31.000Z,NaN,...,NaN,evtticktyp-PFND000001,Pre-Founder,https://linkedin.com/in/harley-ferrari-742,Meta,VP Product,https://github.com/harley-ferrari/open-source-lib,Created a developer tool that reduced onboardi...,Network with engineers building at the frontier.,Agreed

#Renaming cols

In [2]:
luma_hackathon_checkins.columns

Index(['api_id', 'name', 'first_name', 'last_name', 'email', 'phone_number',
       'created_at', 'approval_status', 'checked_in_at', 'custom_source',
       'qr_code_url', 'amount', 'amount_tax', 'amount_discount', 'currency',
       'coupon_code', 'eth_address', 'solana_address',
       'survey_response_rating', 'survey_response_feedback', 'ticket_type_id',
       'ticket_name', 'What is your LinkedIn profile?',
       'What company do you work for?', 'What is your job title?',
       'Link to something you've built',
       'Whats your most impressive achievement in the last 3 years?',
       'What is your main goal for this hackathon?', 'Terms and Conditions'],
      dtype='object')

In [3]:
luma_hackathon_checkins.rename(columns= {
    "What is your LinkedIn profile?" : "linkedin_profile",
    "What company do you work for?" : "company",
    "What is your job title?" : "job_title",
    "Link to something you've built" : "link_to_something_they_built",
    "Whats your most impressive achievement in the last 3 years?" : "most_impressive_achievement_last_3_yrs",
    "What is your main goal for this hackathon?" : "main_hackathon_goal",
}, inplace=True)

luma_hackathon_checkins.head(3)

,api_id,name,first_name,last_name,email,phone_number,created_at,approval_status,checked_in_at,custom_source,...,survey_response_feedback,ticket_type_id,ticket_name,linkedin_profile,company,job_title,link_to_something_they_built,most_impressive_achievement_last_3_yrs,main_hackathon_goal,Terms and Conditions
0,gst-GoEd9Sf53GRx8ffi,Cameron Martin,Cameron,Martin,cameronmar@pm.me,NaN,2026-02-18T15:15:48.000Z,approved,2026-02-21T02:52:18.000Z,NaN,...,Best hackathon I have been to in London. Will ...,evtticktyp-ENG0000001,Engineer,https://linkedin.com/in/cameron-martin-748,Stripe,ML Engineer,https://huggingface.co/spaces/cameron-martin,Led technical due diligence for a €20M Series ...,Find a co-founder with complementary skills.,Agreed
1,gst-hwVCC0fYsRLn1jS8,Diego Yilmaz,Diego,Yilmaz,diego12@hey.com,NaN,2026-02-16T19:18:59.000Z,approved,2026-02-21T00:47:01.000Z,NaN,...,Amazing community. The talks before hacking st...,evtticktyp-ENG0000001,Engineer,https://linkedin.com/in/diego-yilmaz-346,Klarna,Solutions Architect,NaN,Rebuilt the data platform for a Series B start...,Build something I can show to early customers.,Agreed
2,gst-4e9mOYf0Yh6d5ASE,Harley Ferrari,Harley,Ferrari,harleyfer@gmail.com,NaN,2026-02-17T11:06:20.000Z,approved,2026-02-21T02:44:31.000Z,NaN,...,NaN,evtticktyp-PFND000001,Pre-Founder,https://linkedin.com/in/harley-ferrari-742,Meta,VP Product,https://github.com/harley-ferrari/open-source-lib,Created a developer tool that reduced onboardi...,Network with engineers building at the frontier.,Agreed

In [4]:
beehiv.columns

Index(['id', 'email', 'status', 'created', 'subscription_tier', 'utm_source',
       'utm_medium', 'utm_channel', 'utm_campaign', 'referring_site',
       'referral_code', 'tags', 'stats.emails_received', 'stats.open_rate',
       'stats.click_through_rate', 'custom_fields.first_name',
       'custom_fields.last_name'],
      dtype='object')

In [5]:
beehiv.rename(columns={
    "stats.emails_received" : "stats_emails_received",
    "stats.open_rate" : "stats_open_rate",
    "stats.click_through_rate" : "stats_click_through_rate",
    "custom_fields.first_name" : "first_name",
    "custom_fields.last_name" : "last_name"
}, inplace=True)

beehiv.head(3)

,id,email,status,created,subscription_tier,utm_source,utm_medium,utm_channel,utm_campaign,referring_site,referral_code,tags,stats_emails_received,stats_open_rate,stats_click_through_rate,first_name,last_name
0,sub_caa52a2c-518e-407d-bfd5-b7ac2a760e13,cameronmar@pm.me,active,1762761393,free,referral,NaN,social,NaN,techeurope.io,4XlYbIHY,"[""Active"", ""Engaged""]",8,85.0,24.6,Cameron,Martin
1,sub_6086f7b2-dcfb-4f28-9b5a-6ffbb795c261,diego12@hey.com,active,1773078262,free,NaN,social,social,partner_collab,twitter.com,NaN,"[""Active"", ""Engaged"", ""CoFounderMatching""]",9,71.2,18.9,Diego,Yilmaz
2,sub_cb212c6c-d851-4f5e-9221-7c81206b6205,aiko.choi@hey.com,active,1762722502,free,twitter,organic,social,partner_collab,linkedin.com,pUfhs7k8,"[""Active"", ""CoFounderMatching""]",9,38.0,11.0,Aiko,Choi

In [6]:
tally_cofounder.columns

Index(['Submission ID', 'Respondent ID', 'Submitted at', 'Name', 'LinkedIn',
       '(Previous) Role', 'Location',
       'Do you already have a specific problem space in mind?',
       'Provide a brief description',
       'What are your preferred areas to build in?',
       'When are you available full-time?',
       'What is your Email (for contact purposes)?',
       'Do you want to be included in our newsletter (anonymized)?',
       'Provide a short description about yourself/your project and what you are looking for',
       'Untitled long answer field'],
      dtype='object')

In [7]:
tally_cofounder.rename(columns = {
    "Submission ID": "submission_id",
    "Respondent ID": "respondent_id",
    "Submitted at": "submitted_at",
    "Name": "name",
    "LinkedIn": "linkedin",
    "(Previous) Role": "previous_role",
    "Location": "location",
    "Do you already have a specific problem space in mind?": "has_problem_space",
    "Provide a brief description": "problem_space_description",
    "What are your preferred areas to build in?": "preferred_build_areas",
    "When are you available full-time?": "availability",
    "What is your Email (for contact purposes)?": "email",
    "Do you want to be included in our newsletter (anonymized)?": "newsletter_opt_in",
    "Provide a short description about yourself/your project and what you are looking for": "looking_for_description",
    "Untitled long answer field": "extra_notes"
}, inplace=True)

In [8]:
tally_hackathon_submissions.head(3)

,Submission ID,Respondent ID,Submitted at,Email,Team Name,All Team Members (Name + Email),What are you building?,Which of the partner technologies have you used?,Which of the partner technologies have you used? (Deepmind),Which of the partner technologies have you used? (CodeWords (Side Challenge)),Which of the partner technologies have you used? (Lovable),Which of the partner technologies have you used? (Dust),Which track are you competing in?,Which track are you competing in? (Conduct),Which track are you competing in? (Open Innovation),GitHub Repo (Must be public),Demo Video Link (Loom Preferred)
0,HPZaggB,nrlbf6O,2026-02-21 16:25:32,natalia_sousa@icloud.com,RepoSense,Natalia Sousa (natalia_sousa@icloud.com)\nSkyl...,Maps technical debt across any GitHub repo and...,"CodeWords (Side Challenge), Deepmind, Dust, Lo...",True,True,True,True,Conduct,True,False,https://github.com/natalia-sousa/reposense,https://www.loom.com/share/Z6NRh1iO3J73RpC6N5r...
1,lEiVnN4,SgeJpB3,2026-02-21 16:47:12,qwatanabe@hey.com,MediRoute,Quinn Watanabe (qwatanabe@hey.com)\nNadia Bern...,AI triage assistant for GP practices that clas...,"CodeWords (Side Challenge), Deepmind, Lovable",True,True,True,False,Open Innovation,False,True,https://github.com/quinn-watanabe/mediroute,https://www.loom.com/share/jN5PqR4JF6EB0WWHa7Y...
2,7OsygQE,2Blcb9o,2026-02-21 15:10:44,jamiemar@pm.me,LexAI,Jamie Martin (jamiemar@pm.me)\nPawel Ferrari (...,Browser extension that summarises legal T&Cs i...,"CodeWords (Side Challenge), Deepmind, Lovable",True,True,True,False,Open Innovation,False,True,https://github.com/jamie-martin/lexai,https://www.loom.com/share/yXNE7Y7bvuSznOG61HT...

In [9]:
tally_hackathon_submissions.rename(columns=
    {
    "Submission ID": "submission_id",
    "Respondent ID": "respondent_id",
    "Submitted at": "submitted_at",
    "Email": "email",
    "Team Name": "team_name",
    "All Team Members (Name + Email)": "all_team_members",
    "What are you building?": "project_description",
    "Which of the partner technologies have you used?": "technologies_used",
    "Which of the partner technologies have you used? (Deepmind)": "tech_deepmind",
    "Which of the partner technologies have you used? (CodeWords (Side Challenge))": "tech_codewords",
    "Which of the partner technologies have you used? (Lovable)": "tech_lovable",
    "Which of the partner technologies have you used? (Dust)": "tech_dust",
    "Which track are you competing in?": "track",
    "Which track are you competing in? (Conduct)": "track_conduct",
    "Which track are you competing in? (Open Innovation)": "track_open_innovation",
    "GitHub Repo (Must be public)": "github_repo",
    "Demo Video Link (Loom Preferred)": "demo_video"
},inplace=True)

tally_hackathon_submissions.head(3)

,submission_id,respondent_id,submitted_at,email,team_name,all_team_members,project_description,technologies_used,tech_deepmind,tech_codewords,tech_lovable,tech_dust,track,track_conduct,track_open_innovation,github_repo,demo_video
0,HPZaggB,nrlbf6O,2026-02-21 16:25:32,natalia_sousa@icloud.com,RepoSense,Natalia Sousa (natalia_sousa@icloud.com)\nSkyl...,Maps technical debt across any GitHub repo and...,"CodeWords (Side Challenge), Deepmind, Dust, Lo...",True,True,True,True,Conduct,True,False,https://github.com/natalia-sousa/reposense,https://www.loom.com/share/Z6NRh1iO3J73RpC6N5r...
1,lEiVnN4,SgeJpB3,2026-02-21 16:47:12,qwatanabe@hey.com,MediRoute,Quinn Watanabe (qwatanabe@hey.com)\nNadia Bern...,AI triage assistant for GP practices that clas...,"CodeWords (Side Challenge), Deepmind, Lovable",True,True,True,False,Open Innovation,False,True,https://github.com/quinn-watanabe/mediroute,https://www.loom.com/share/jN5PqR4JF6EB0WWHa7Y...
2,7OsygQE,2Blcb9o,2026-02-21 15:10:44,jamiemar@pm.me,LexAI,Jamie Martin (jamiemar@pm.me)\nPawel Ferrari (...,Browser extension that summarises legal T&Cs i...,"CodeWords (Side Challenge), Deepmind, Lovable",True,True,True,False,Open Innovation,False,True,https://github.com/jamie-martin/lexai,https://www.loom.com/share/yXNE7Y7bvuSznOG61HT...

In [10]:
tally_weekly_contact.columns

Index(['Submission ID', 'Respondent ID', 'Submitted at', 'Your Name',
       'Your Email', 'Your LinkedIn',
       'Who of this weeks candidates would you like to have a chat with',
       'Why do you think there is a fit?'],
      dtype='object')

In [11]:
tally_weekly_contact.rename(columns={
        "Submission ID": "submission_id",
    "Respondent ID": "respondent_id",
    "Submitted at": "submitted_at",
    "Your Name": "name",
    "Your Email": "email",
    "Your LinkedIn": "linkedin",
    "Who of this weeks candidates would you like to have a chat with": "connection_request_roles",
    "Why do you think there is a fit?": "connection_request_reason"
}, inplace=True)

tally_weekly_contact.head(3)

,submission_id,respondent_id,submitted_at,name,email,linkedin,connection_request_roles,connection_request_reason
0,3sFHero,hwHuPpU,2026-03-13 12:22:07,Cameron Martin,cameronmar@pm.me,https://linkedin.com/in/cameron-martin-748,AI Researcher,Would love to understand how they approached s...
1,4asYWzz,JODFVjy,2026-03-12 14:31:43,Diego Yilmaz,diego12@hey.com,https://linkedin.com/in/diego-yilmaz-346,Backend Engineer,I am a full-stack engineer and have been looki...
2,SCXtlVR,mBIxJh6,2026-03-12 20:07:49,Aiko Choi,aiko.choi@hey.com,https://linkedin.com/in/aiko-choi-256,"Head of Growth, ML Engineer",I have been building in this exact space and w...

In [12]:
print(tally_hackathon_submissions["all_team_members"].iloc[0])

Natalia Sousa (natalia_sousa@icloud.com)
Skyler Yamamoto (skyler_yamamoto@icloud.com)
Kendall Kaya (kendall44@outlook.com)

#getting the names and emails of the all_team_members

In [13]:
def parse_team_member(cell):
    
    chunks = cell.split("\n")
    result = []
    
    for chunk in chunks:
        name = chunk[:chunk.find("(")].strip()
        email = chunk[chunk.find("(")+1:chunk.find(")")]
        result.append((name , email))
    return result

print(parse_team_member(cell))

NameError: name 'cell' is not defined

In [ ]:
tally_hackathon_submissions["parsed_members"] = tally_hackathon_submissions["all_team_members"].apply(parse_team_member)

tally_hackathon_submissions = tally_hackathon_submissions.explode("parsed_members")

tally_hackathon_submissions[["member_name", "email"]] = pd.DataFrame(
    tally_hackathon_submissions["parsed_members"].tolist(), index=tally_hackathon_submissions.index
)

tally_hackathon_submissions[["member_name", "email", "parsed_members"]].head(10)

,member_name,email,parsed_members
0,Natalia Sousa,natalia_sousa@icloud.com,"(Natalia Sousa, natalia_sousa@icloud.com)"
0,Skyler Yamamoto,skyler_yamamoto@icloud.com,"(Skyler Yamamoto, skyler_yamamoto@icloud.com)"
0,Kendall Kaya,kendall44@outlook.com,"(Kendall Kaya, kendall44@outlook.com)"
1,Quinn Watanabe,qwatanabe@hey.com,"(Quinn Watanabe, qwatanabe@hey.com)"
1,Nadia Bernard,nadiaber@icloud.com,"(Nadia Bernard, nadiaber@icloud.com)"
1,Mira Ferrari,mira_ferrari@fastmail.com,"(Mira Ferrari, mira_ferrari@fastmail.com)"
2,Jamie Martin,jamiemar@pm.me,"(Jamie Martin, jamiemar@pm.me)"
2,Pawel Ferrari,pawel79@hey.com,"(Pawel Ferrari, pawel79@hey.com)"
2,Soren Santos,ssantos@gmail.com,"(Soren Santos, ssantos@gmail.com)"
2,Vera Klein,vera62@proton.me,"(Vera Klein, vera62@proton.me)"